### ISSUE TITLE
update-grub doesn't work without /mnt/boot/zfsenv

### ISSUE THREAD

**Issue by a-schaefers** [johnramsden/zedenv#10]
legacy system using grub plugin. The only /etc/grub.d files executeable are 00_header and the zedenv file.

```
# update-grub
Generating grub configuration file ...
Traceback (most recent call last):
  File "/etc/grub.d/05_zfs_linux.py", line 718, in <module>
    grub = Generator()
  File "/etc/grub.d/05_zfs_linux.py", line 572, in __init__
    self.boot_list = self.get_boot_environments_boot_list()
  File "/etc/grub.d/05_zfs_linux.py", line 632, in get_boot_environments_boot_list
    for e in os.listdir(self.boot_env_kernels)]
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/boot/zfsenv'
root@e6430:~# mkdir /mnt/boot/zfsenv
```

The debian system I am testing zedenv had /mnt/boot but not /mnt/boot/zfsenv.
I did mkdir /mnt/boot/zfsenv and update-grub worked as expected after that.

edit: It was completely disastrous because this bug causes "apt upgrade" to bail out of operations.
If the installation method is relevant, i cloned all the repos and used "python setup.py install"

**Comment by johnramsden** [comment]
Could you re-open this in [zedenv-grub](https://github.com/johnramsden/zedenv-grub/issues/new)?

**Comment by johnramsden** [comment]
Had to make some changes here too, so you can leave this open.

**Comment by a-schaefers** [comment]
> Could you re-open this in [zedenv-grub](https://github.com/johnramsden/zedenv-grub/issues/new)?

https://github.com/johnramsden/zedenv-grub/issues/12

**Comment by johnramsden** [comment]
Okay, I think I got this fixed. I had to add a patch to zedenv in order to create a PID file so I can check if activate is currently being run. Are you able to test the patch and let me know if it fixes the problem for you? You will have to clone the branches [zedenv/grub](https://github.com/johnramsden/zedenv/tree/grub) and [zedenv-grub/run-once](https://github.com/johnramsden/zedenv-grub/tree/run-once)

**Comment by a-schaefers** [comment]
Okay, tested on those branches and all is working without a trouble now. Cool stuff man.

**Comment by johnramsden** [comment]
Thanks Adam.
