### ISSUE TITLE
zfs-auto-snapshot conflict

### ISSUE THREAD

**Issue by a-schaefers** [johnramsden/zedenv#12]
After installing and enabling [zfs-auto-snapshot](https://github.com/zfsonlinux/zfs-auto-snapshot), typing update-grub fails.

> root@e6430:/etc/default#
> 
>  sudo !!
> sudo update-grub
> Generating grub configuration file ...
> /mnt/boot/zfsenv/zedenv-testing
> Failed mounting dataset to '/mnt/boot/zfsenv/zedenv-root@zfs-auto-snap_frequent-2018-11-08-0845'.
> Failed to get mount data.
> Command '['mount', '-t', 'zfs', '-o', 'zfsutil', 'rpool/root/root@zfs-auto-snap_frequent-2018-11-08-0845', '/mnt/boot/zfsenv/zedenv-root@zfs-auto-snap_frequent-2018-11-08-0845']' returned non-zero exit status 1.
> .
> 1
> root@e6430:/etc/default#

FYI what follows is a current listing via zfs list -t snap:

> rpool@zfs-auto-snap_frequent-2018-11-08-0845                   0B      -    96K  -
> rpool@zfs-auto-snap_frequent-2018-11-08-0900                  0B      -    96K  -
> rpool@zfs-auto-snap_frequent-2018-11-08-0915                  0B      -    96K  -
> rpool@zfs-auto-snap_hourly-2018-11-08-0917                    0B      -    96K  -
> rpool@zfs-auto-snap_frequent-2018-11-08-0930                  0B      -    96K  -
> rpool/boot@zfs-auto-snap_frequent-2018-11-08-0845             0B      -    96K  -
> rpool/boot@zfs-auto-snap_frequent-2018-11-08-0900             0B      -    96K  -
> rpool/boot@zfs-auto-snap_frequent-2018-11-08-0915             0B      -    96K  -
> rpool/boot@zfs-auto-snap_hourly-2018-11-08-0917               0B      -    96K  -
> rpool/boot@zfs-auto-snap_frequent-2018-11-08-0930             0B      -    96K  -
> rpool/boot/grub@zfs-auto-snap_frequent-2018-11-08-0845        0B      -  7.48M  -
> rpool/boot/grub@zfs-auto-snap_frequent-2018-11-08-0900        0B      -  7.48M  -
> rpool/boot/grub@zfs-auto-snap_frequent-2018-11-08-0915        0B      -  7.48M  -
> rpool/boot/grub@zfs-auto-snap_hourly-2018-11-08-0917          0B      -  7.48M  -
> rpool/boot/grub@zfs-auto-snap_frequent-2018-11-08-0930        8K      -  7.48M  -
> rpool/ext4_backup@zfs-auto-snap_frequent-2018-11-08-0845      0B      -  11.1G  -
> rpool/ext4_backup@zfs-auto-snap_frequent-2018-11-08-0900      0B      -  11.1G  -
> rpool/ext4_backup@zfs-auto-snap_frequent-2018-11-08-0915      0B      -  11.1G  -
> rpool/ext4_backup@zfs-auto-snap_hourly-2018-11-08-0917        0B      -  11.1G  -
> rpool/ext4_backup@zfs-auto-snap_frequent-2018-11-08-0930      0B      -  11.1G  -
> rpool/home@zfs-auto-snap_frequent-2018-11-08-0845             0B      -    96K  -
> rpool/home@zfs-auto-snap_frequent-2018-11-08-0900             0B      -    96K  -
> rpool/home@zfs-auto-snap_frequent-2018-11-08-0915             0B      -    96K  -
> rpool/home@zfs-auto-snap_hourly-2018-11-08-0917               0B      -    96K  -
> rpool/home@zfs-auto-snap_frequent-2018-11-08-0930             0B      -    96K  -
> rpool/home/adam@zfs-auto-snap_frequent-2018-11-08-0845     9.57M      -  1.35G  -
> rpool/home/adam@zfs-auto-snap_frequent-2018-11-08-0900     2.46M      -  1.35G  -
> rpool/home/adam@zfs-auto-snap_frequent-2018-11-08-0915     1.79M      -  1.35G  -
> rpool/home/adam@zfs-auto-snap_hourly-2018-11-08-0917       3.42M      -  1.35G  -
> rpool/home/adam@zfs-auto-snap_frequent-2018-11-08-0930     4.32M      -  1.35G  -
> rpool/root@zfs-auto-snap_frequent-2018-11-08-0845             0B      -    96K  -
> rpool/root@zfs-auto-snap_frequent-2018-11-08-0900             0B      -    96K  -
> rpool/root@zfs-auto-snap_frequent-2018-11-08-0915             0B      -    96K  -
> rpool/root@zfs-auto-snap_hourly-2018-11-08-0917               0B      -    96K  -
> rpool/root@zfs-auto-snap_frequent-2018-11-08-0930             0B      -    96K  -
> rpool/root/stable@2018-11-07-01-920008                      200M      -  2.01G  -
> rpool/root/stable@zfs-auto-snap_frequent-2018-11-08-0845    420K      -  1.87G  -
> rpool/root/stable@zfs-auto-snap_frequent-2018-11-08-0900    392K      -  1.87G  -
> rpool/root/stable@zfs-auto-snap_frequent-2018-11-08-0915    352K      -  1.87G  -
> rpool/root/stable@zfs-auto-snap_hourly-2018-11-08-0917      356K      -  1.87G  -
> rpool/root/stable@zfs-auto-snap_frequent-2018-11-08-0930   20.9M      -  1.87G  -
> rpool/root/testing@zfs-auto-snap_frequent-2018-11-08-0845     0B      -  2.13G  -
> rpool/root/testing@zfs-auto-snap_frequent-2018-11-08-0900     0B      -  2.13G  -
> rpool/root/testing@zfs-auto-snap_frequent-2018-11-08-0915     0B      -  2.13G  -
> rpool/root/testing@zfs-auto-snap_hourly-2018-11-08-0917       0B      -  2.13G  -
> rpool/root/testing@zfs-auto-snap_frequent-2018-11-08-0930     0B      -  2.13G  -

**Comment by a-schaefers** [comment]
workaround was to destroy all of the zfs-auto-snapshots and rm -rf /mnt/boot/zfsenv/zedenv-root@zfs-auto-snap_frequent-2018-11-08-0845

**Comment by johnramsden** [comment]
I think I know where this occurs, but haven't been able to reproduce it. Would you be able to see if this branch fixes it: [zedenv-grub/nomountsnap](https://github.com/johnramsden/zedenv-grub/tree/nomountsnap)

**Comment by a-schaefers** [comment]
I reinstalled zedenv-grub using the nomountsnap branch, then I did what follows:

```
adam@e6430:~/repos/zedenv-grub$ sudo update-grub
Generating grub configuration file ...
Traceback (most recent call last):
  File "/etc/grub.d/05_zfs_linux.py", line 773, in <module>
    for en in Generator().generate_grub_entries():
  File "/etc/grub.d/05_zfs_linux.py", line 578, in __init__
    self.boot_list = self.get_boot_environments_boot_list()
  File "/etc/grub.d/05_zfs_linux.py", line 638, in get_boot_environments_boot_list
    for e in os.listdir(self.boot_env_kernels)]
  File "/etc/grub.d/05_zfs_linux.py", line 638, in <listcomp>
    for e in os.listdir(self.boot_env_kernels)]
  File "/etc/grub.d/05_zfs_linux.py", line 609, in create_entry
    boot_files = os.listdir(boot_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/boot/zfsenv/zedenv-root@zfs-auto-snap_frequent-2018-11-08-1945/boot'
1
adam@e6430:~/repos/zedenv-grub$ ls /mnt/boot/zfsenv/
zedenv-root@zfs-auto-snap_frequent-2018-11-08-1945  zedenv-testing
```

**Comment by johnramsden** [comment]
What shows up with `zedenv list`?

**Comment by johnramsden** [comment]
Do you know if the snapshot directory existed before you ran the update command? Can you unmount everything under `/mnt/boot/zfsenv/`, delete the directories and try again?

```
umount -R /mnt/boot/zfsenv
rm -r /mnt/boot/zfsenv
```

**Comment by a-schaefers** [comment]
interesting, ok after unmounting everything under /mnt/boot/zfsenv and removing the zfsenv directory entirely (now /mnt/boot is the only thing that exists) , update-grub and zedenv create/destroy/activate are all working as expected.

There are now no other files or directories under /mnt/boot. Is this normal behavior?

**Comment by johnramsden** [comment]
Yes that's expected. It creates the directory and then cleans up when it's finished. It leaves them around if you're not using boot on ZFS.

Just to verify, does it work if you have snapshots now?

**Comment by a-schaefers** [comment]
On my last tests, everything worked fine using zfs auto snapshots, but only with the new branch (nomountsnap).

**Comment by johnramsden** [comment]
Awesome thanks. I'll merge it into master.

**Comment by johnramsden** [comment]
Opened a bug in zedenv-grub so I can reference it it in the fix.

https://github.com/johnramsden/zedenv-grub/issues/14
