### ISSUE TITLE
zedenv description

### ISSUE THREAD

**Issue by danboid** [johnramsden/zedenv#13]
zedenv's description on the AUR currently is:

"Utility to manage Boot Environments using ZFS"

I think that's slightly incorrectly worded, shouldn't it be

"Utility to manage ZFS Boot Environments"

It seems the GRUB plugin is still missing from the AUR - I presume you've just not had the time to upload it yet?

**Comment by johnramsden** [comment]
You're probably right, i'll modify the description.

I haven't added it to the AUR since I was a little hesitant due to the code being so fresh but it's probably ready, and if there are bugs they shouldn't be catastrophic.

**Comment by johnramsden** [comment]
@danboid https://aur.archlinux.org/packages/zedenv-grub/

**Comment by danboid** [comment]
Thanks John!
