### ISSUE TITLE
"zedenv destroy" fails if LC_TIME is not C

### ISSUE THREAD

**Issue by TPKato** [johnramsden/zedenv#15]
zedenv fails destroying a BE if LC_TIME is not C (e.g. de_DE.UTF-8 (german)).
I think it's better if LC_TIME (or LC_ALL ?) is set to "C" in the script.

    # zedenv create x
    
    # env LC_ALL="" LC_TIME=de_DE.UTF-8 zedenv destroy x
    Do you really want to destroy 'x'?
    This action will be permanent.
    
    Destroy 'zroot/ROOT/x'? [y/N]: y
    
    Traceback (most recent call last):
      File "/usr/lib/python3.7/site-packages/zedenv/cli/destroy.py", line 105, in get_clone_origin
        "%a %b %d %H:%M %Y")
      File "/usr/lib/python3.7/_strptime.py", line 577, in _strptime_datetime
        tt, fraction, gmtoff_fraction = _strptime(data_string, format)
      File "/usr/lib/python3.7/_strptime.py", line 359, in _strptime
        (data_string, format))
    ValueError: time data 'Do Nov 29 18:11 2018' does not match format '%a %b %d %H:%M %Y'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/bin/zedenv", line 11, in <module>
        load_entry_point('zedenv==0.3.3', 'console_scripts', 'zedenv')()
      File "/usr/lib/python3.7/site-packages/click/core.py", line 764, in __call__
        return self.main(*args, **kwargs)
      File "/usr/lib/python3.7/site-packages/click/core.py", line 717, in main
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/bin/zedenv", line 11, in <module>
        load_entry_point('zedenv==0.3.3', 'console_scripts', 'zedenv')()
      File "/usr/lib/python3.7/site-packages/click/core.py", line 764, in __call__
        return self.main(*args, **kwargs)
      File "/usr/lib/python3.7/site-packages/click/core.py", line 717, in main
        rv = self.invoke(ctx)
      File "/usr/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/usr/lib/python3.7/site-packages/click/core.py", line 956, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
        return callback(*args, **kwargs)
      File "/usr/lib/python3.7/site-packages/zedenv/cli/destroy.py", line 364, in cli
        noop)
      File "/usr/lib/python3.7/site-packages/zedenv/cli/destroy.py", line 281, in zedenv_destroy
        clone_origin = get_clone_origin(destroy_dataset)
      File "/usr/lib/python3.7/site-packages/zedenv/cli/destroy.py", line 109, in get_clone_origin
        "message": f"Failed to parse time from origin {origin_property}\n{e}"
    UnboundLocalError: local variable 'e' referenced before assignment
    
    # env LC_ALL=C zedenv destroy x
    (success)

(FYI: )

    # env LC_ALL= LC_TIME=de_DE.UTF-8 date
    Do 29. Nov 18:28:59 CET 2018
    # env LC_ALL=C date
    Thu Nov 29 18:29:05 CET 2018

**Comment by johnramsden** [comment]
I'm having some trouble reproducing this

```
env LC_ALL="" LC_TIME=de_DE.UTF-8 zedenv destroy -v x
Do you really want to destroy 'x'?
This action will be permanent.

Destroy 'vault/sys/enix/ROOT/x'? [y/N]: y

Configuring boot environment bootloader with systemdboot

Checking prop: 'org.zedenv.systemdboot:esp'
esp set to /mnt/efi

Using plugin systemdboot

Boot environment 'x' is a clone.
Checking to make sure there are no dependant clones to promote.

The origin snapshot '2018-11-29-15-632357' for the boot environment 'x' still exists, do you want to destroy it? This action will be permanent.

Destroy 'vault/sys/enix/ROOT/linux-4.19.4-plasma-5.14.4@2018-11-29-15-632357'? [y/N]: y

Destroyed vault/sys/enix/ROOT/linux-4.19.4-plasma-5.14.4@2018-11-29-15-632357.

Destroyed boot environment x successfully.
```

However, from now on I will set the locale before parsing and setting the time format. Hopefully that fixes the issue for you.

@TPKato If I have a possible fix would you be able to test out the new branch?

**Comment by johnramsden** [comment]
Although I was unable to reproduce it, If you're able to test it, [I pushed a new commit](zedenv/tree/issue/15) that I believe fixes the locale problem.

**Comment by TPKato** [comment]
Thank you for your reply.

Unfortunately, it seems that this patch does not work well, even if `LC_TIME` is `C`.

    # locale
    LANG=ja_JP.UTF-8
    LC_CTYPE="C"
    LC_NUMERIC="C"
    LC_TIME="C"
    LC_COLLATE="C"
    LC_MONETARY="C"
    LC_MESSAGES="C"
    LC_PAPER="C"
    LC_NAME="C"
    LC_ADDRESS="C"
    LC_TELEPHONE="C"
    LC_MEASUREMENT="C"
    LC_IDENTIFICATION="C"
    LC_ALL=C

    # zedenv create x
    # zedenv destroy x

will fail with a message:

    Failed to parse time from origin zroot/ROOT/BE20181130@2018-11-30-12-462705

I think

    origin_datetime = zedenv.lib.system.parse_time( origin_property.split('@')[1].split("-", 1)[1])

in `zedenv/cli/destroy.py` should be

    origin_datetime = zedenv.lib.system.parse_time(origin_property.split('@')[1])

shouldn't it?
(otherwise `origin_datetime` will be `2018` instead of `2018-11-30-12-462705`)

If I apply this modification and try to destroy `x` again, then I get still an exception.
(The line numbers are NOT correct, because I added some `print()`s in this file.)

    Traceback (most recent call last):
      File "/tmp/z/lib/python/zedenv-0.3.3-py3.7.egg/zedenv/cli/destroy.py", line 111, in get_clone_origin
        creation_datetime = zedenv.lib.system.parse_time(creation_property)
      File "/tmp/z/lib/python/zedenv-0.3.3-py3.7.egg/zedenv/lib/system.py", line 26, in parse_time
        origin_datetime: datetime = datetime.datetime.strptime(origin_property, fmt)
      File "/usr/lib/python3.7/_strptime.py", line 577, in _strptime_datetime
        tt, fraction, gmtoff_fraction = _strptime(data_string, format)
      File "/usr/lib/python3.7/_strptime.py", line 359, in _strptime
        (data_string, format))
    ValueError: time data 'Fr Nov 30 12:55 2018' does not match format '%Y-%m-%d-%H-%f'

As you see, the value of `creation_prop` is `Fr Nov 30 12:55 2018`, not `2018-11-30-12-462705`.

**Comment by TPKato** [comment]
To reproduce the problem:
Could you try `locale` command to check if `LC_*` are correctly set?
(`locale` command is included in the base system of ArchLinux. I don't know if this command exists in other systems, too.)
In my environment, it generates the following results:

    # env LC_ALL="" LC_TIME=de_DE.UTF-8 locale
    LANG=ja_JP.UTF-8
    LC_CTYPE="ja_JP.UTF-8"
    LC_NUMERIC="ja_JP.UTF-8"
    LC_TIME=de_DE.UTF-8
    LC_COLLATE="ja_JP.UTF-8"
    LC_MONETARY="ja_JP.UTF-8"
    LC_MESSAGES=C
    LC_PAPER="ja_JP.UTF-8"
    LC_NAME="ja_JP.UTF-8"
    LC_ADDRESS="ja_JP.UTF-8"
    LC_TELEPHONE="ja_JP.UTF-8"
    LC_MEASUREMENT="ja_JP.UTF-8"
    LC_IDENTIFICATION="ja_JP.UTF-8"
    LC_ALL=

    # env LC_ALL=C locale
    LANG=ja_JP.UTF-8
    LC_CTYPE="C"
    LC_NUMERIC="C"
    LC_TIME="C"
    LC_COLLATE="C"
    LC_MONETARY="C"
    LC_MESSAGES="C"
    LC_PAPER="C"
    LC_NAME="C"
    LC_ADDRESS="C"
    LC_TELEPHONE="C"
    LC_MEASUREMENT="C"
    LC_IDENTIFICATION="C"
    LC_ALL=C

**Comment by johnramsden** [comment]
Yeah I didn't have `de_DE.UTF-8` enabled in my `/etc/locale.gen`. I enabled it, and I was able to reproduce the bug.

**Comment by johnramsden** [comment]
When you run the current release with your systems default locale, does everything work? Or is your default local already `de_DE.UTF-8`?

**Comment by TPKato** [comment]
> When you run the current release with your systems default locale, does everything work?

Yes.
If I login as root directly (not via `su` or `sudo`), the default locale is `en_US.UTF-8` and everything works fine.

    # cat /etc/locale.conf
    LANG=en_US.UTF-8
    
    # locale
    LANG=en_US.UTF-8
    LC_CTYPE="en_US.UTF-8"
    LC_NUMERIC="en_US.UTF-8"
    LC_TIME="en_US.UTF-8"
    LC_COLLATE="en_US.UTF-8"
    LC_MONETARY="en_US.UTF-8"
    LC_MESSAGES="en_US.UTF-8"
    LC_PAPER="en_US.UTF-8"
    LC_NAME="en_US.UTF-8"
    LC_ADDRESS="en_US.UTF-8"
    LC_TELEPHONE="en_US.UTF-8"
    LC_MEASUREMENT="en_US.UTF-8"
    LC_IDENTIFICATION="en_US.UTF-8"
    LC_ALL=

    # zedenv create x
    # zedenv destroy x
    (success)

> Or is your default local already `de_DE.UTF-8`?

No. I set some variables in my `~/.bashrc` as follows:

    export LANG=ja_JP.UTF-8
    export LC_MESSAGES=C
    export LC_TIME=de_DE.UTF-8

If I become root using `su`, then `zedenv destroy` fails because of `LC_TIME=de_DE.UTF-8`.

    $ su
    # locale | grep TIME
    LC_TIME=de_DE.UTF-8		(inherited from my ~/.bashrc settings. /root/.bashrc does not exist.)

    # zedenv create x
    # zedenv destroy x
    (fails as I reported)

Now I've added

    export LC_ALL=C

in `/root/.bashrc`, so `zedenv destroy` works correctly.

    $ su
    # locale | grep TIME
    LC_TIME="C"			(because of LC_ALL=C in /root/.bashrc)

    # zedenv create x
    # zedenv destroy x
    (success)

The version of `zedenv` is 0.3.3.
I've installed it using AUR (ArchLinux).

    # zedenv --version
    Version 0.3.3
    # pacman -Qs zedenv                                                                                                     
    local/zedenv 0.3.3-1
        Utility to manage Boot Environments using ZFS

**Comment by johnramsden** [comment]
I believe I have fixed this now. Part of the problem was when setting the locale, it doesn't get respected in subprocesses, so the creation date wasn't matching the newly set `C` locale when asking for the creation date from `zfs get`. I added the ability to set the locale in johnramsden/pyzfscmds@b039f1d when running `zfs get`.

That combined with setting the locale when parsing the date in `zedenv`, and it seems to work for me when using `de_DE.UTF-8`.

@TPKato Do you think you'd be able to try the changes again from the [`issue/15`](https://github.com/johnramsden/zedenv/tree/issue/15) branch? You will need to update your version of pyzfscmds, but I pushed a new version to the AUR, so you should just be able update your system package.

**Comment by TPKato** [comment]
It works fine. Thanks!

    # env LC_ALL="" LC_TIME=de_DE.UTF-8 locale
    LANG=ja_JP.UTF-8
    LC_CTYPE="ja_JP.UTF-8"
    LC_NUMERIC="ja_JP.UTF-8"
    LC_TIME=de_DE.UTF-8
    LC_COLLATE="ja_JP.UTF-8"
    LC_MONETARY="ja_JP.UTF-8"
    LC_MESSAGES=C
    LC_PAPER="ja_JP.UTF-8"
    LC_NAME="ja_JP.UTF-8"
    LC_ADDRESS="ja_JP.UTF-8"
    LC_TELEPHONE="ja_JP.UTF-8"
    LC_MEASUREMENT="ja_JP.UTF-8"
    LC_IDENTIFICATION="ja_JP.UTF-8"
    LC_ALL=
    
    # env LC_ALL="" LC_TIME=de_DE.UTF-8 zedenv create x
    # env LC_ALL="" LC_TIME=de_DE.UTF-8 zedenv destroy x
    (successfully destroyed!)

Of course it works fine, when `LC_TIME` is `C`, too:

    # locale
    LANG=ja_JP.UTF-8
    LC_CTYPE="C"
    LC_NUMERIC="C"
    LC_TIME="C"
    LC_COLLATE="C"
    LC_MONETARY="C"
    LC_MESSAGES="C"
    LC_PAPER="C"
    LC_NAME="C"
    LC_ADDRESS="C"
    LC_TELEPHONE="C"
    LC_MEASUREMENT="C"
    LC_IDENTIFICATION="C"
    LC_ALL=C
    
    # zedenv create x 
    # zedenv destroy x
    (success)

FYI:

    # pacman -Qs pyzfscmds 
    local/python-pyzfscmds 0.1.4-1
        ZFS CLI wrapper library
    
    # pacman -Qs zedenv
    local/zedenv-git r158.39e0d65-1
        Utility to manage ZFS Boot Environments

(I modified `PKGBUILD` of `zedenv-git` for `issue/15`-branch and used it to install `zedenv`.)

**Comment by johnramsden** [comment]
Thanks for your help in getting this issue fixed!
