### ISSUE TITLE
zedenv UI

### ISSUE THREAD

**Issue by danboid** [johnramsden/zedenv#18]
It would be nice to have both an ncurses and a GUI eg Qt/pyQt or similar interface to easily manage zedenv BEs with.

I suspect we can borrow the Qt one from PCBSD / TrueOS / whatever they are calling it today with only minor modifications to the source.

**Comment by danboid** [comment]
What are your thoughts John? I'll have a go if this doesn't interest you.

**Comment by danboid** [comment]
It's kinda unrelated but I'd also like a tool to simplify creating pools / formatting single drives as ZFS.

**Comment by johnramsden** [comment]
I think it's a little bit out of the scope of what I planned for the project, and a refactoring would be necessary to simplify external usage with an API. Either that or something could be written that just wraps the CLI.

I don't think I have the time to do this at the moment, but I'll keep it in mind for the future.

**Comment by danboid** [comment]
NP John, I'm happy enough using zedenv via the terminal for the moment.

Thanks!
