### ISSUE TITLE
Unable to create snapshot

### ISSUE THREAD

**Issue by slicer69** [johnramsden/zedenv#2]
When running "zedenv create <snapshot-name> on a pool called "mydata" the command returns the error

"Failed to create snapshot mydata/mydata@2018-05-30"

This appears to be a problem with mydata not having a volume also called "mydata". Ideally, the zedenv command should be trying to create a snapshot called "mydata@2018-05-30".

**Comment by johnramsden** [comment]
How are your datasets setup? Are they in a `<pool>/ROOT/<boot environment>` hierarchy? If not, that might be the problem.

**Comment by johnramsden** [comment]
Yeah that's the problem if your root dataset is installed to `mydata`. Are you able to boot into another system that can use ZFS? You could use your install media that you used to install your system originally.

If so you could rename it to `mydata/ROOT/default`

You would want to import the pool to an altroot, say `/mnt`: 

```
zpool import -d /dev/disk/by-id -R /mnt mydata
```

Rename your root

```shell
zfs rename -p mydata mydata/ROOT/default
zfs set mountpoint=none mydata
zfs set mountpoint=none mydata/ROOT 
```

Make sure your root is set:

```
zfs set mountpoint=/ mydata/ROOT/default
```

Set your bootfs

```
zpool set bootfs=mydata/ROOT/default mydata
```

Then, you need to edit your bootloader config to point to `mydata/ROOT/defaul`t. If you're using systemdboot, find the `zfs=mydata`, and change it to `zfs=mydata/ROOT/default`, if it was set to `zfs=bootfs`, it would probably continue to work but you might want to set it to `zfs=mydata/ROOT/default`.

**Comment by slicer69** [comment]
You are right, Antergos sets up ZFS without any datasets. Unfortunately this also means that setting up a mydata/ROOT/default set will not work. Since there are no data sets there is nothing to rename or shift over to the new location. The above "zfs rename" command and similar steps to create and move the boot point into a new dataset fail. I think we'll just have to acknowledge Antergos won't work with zedenv.

**Comment by johnramsden** [comment]
Hmm, with `-p` I would have thought it would create any parent datasets needed.

You could also just create them manually:

```
zfs create -o mountpoint=none mydata/ROOT
zfs rename mydata mydata/ROOT/default
```

If you can't rename them, you could always send them with:

```
zfs create -o mountpoint=none mydata/ROOT
zfs snapshot mydata@pre-be-snap
zfs send mydata@pre-be-snap | zfs recv mydata/ROOT/default
```

**Comment by slicer69** [comment]
I think, in this case, the zend/recv process is the only one that will work, I'm running into errors trying to create a new set. Thank you for trouble-shooting this.

I've also tried zedenv on FreeBSD. It's working pretty well. It just requires that the LANG environment variable is set before zedenv will run. Otherwise it seems to work just as well as beadm.

**Comment by johnramsden** [comment]
Glad to hear that. It's really a shame antergos defaults to setting their pool like that without letting you customize it. 

Yeah I noticed that I needed to set the Locale and set utf-8 to get it working properly.

**Comment by slicer69** [comment]
Great, I think we can close this bug. I'll just tweak my Antergos set up to see if I can make it match the expected datasets.
