### ISSUE TITLE
Add support for separate ZFS boot pool on second partition

### ISSUE THREAD

**Issue by mkessler001** [johnramsden/zedenv#20]
At the moment, Grub supports only a subset of the ZFS features. This is reason why the [ZoL-Guide](https://github.com/zfsonlinux/zfs/wiki/Ubuntu-18.04-Root-on-ZFS) suggests to use a separate ZFS pool to store grub and the kernel / ramdisk files.

The current version of `zedenv` offers only two modes:
- storing the kernel files within a subfolder of the actual root dataset
- using a second partition with a pre-defined folder structure.

To make this work with a second ZFS pool on a different partition, it requires some fixes in this repository and [`zedenv-grub`](https://github.com/johnramsden/zedenv-grub). I've already looked  in your code and got a working solution. Please see my solution only as suggestion how this problem could be solved. I'm currently in the cleanup phase and I'm going to create a pull request tomorrow for both repositories.

## Current setup

This is the setup I'm using:

- 1st partition EFI
- 2nd partition ZFS - `bpool`

```
bpool/boot/env/zedenv-BE1
bpool/boot/env/zedenv-BE2
bpool/boot/env/zedenv-...
bpool/boot/grub
```
- 3rd partition ZFS - `rpool` (optional, this partition can be encrypted with LUKS)

```
rpool/home
rpool/home/root
rpool/opt
rpool/root
rpool/root/BE1
rpool/root/BE2
rpool/root/...
rpool/var
...
```

## Generating `grub.cfg`

I've set `org.zedenv.grub:boot=/boot` to mount the _boot-env-tree_ temporary at `/boot/zfsenv/zedenv-BE...`. 

`05_zfs_linux.py` uses then the second partition for `set root= ...` and the kernel and ramdisk can be successfully loaded by grub at boot time.

To generate the grub entries, all **boot** datasets (including the current one mounted at `/boot`) are mounted at the temporary subfolder `/boot/zfsenv`.

## Creating / Destroying / Renaming

The same operation is executed to the corresponding **boot** dataset if this mode has been recognized.

## Mount

The **boot** dataset must be mounted after the **root** dataset at `{mountpoint}/boot`.

## Unmount

The **boot** dataset must be unmounted before the **root** dataset.

## Mounting `/boot` at startup

As I'm currently working under Ubuntu, I use _systemd_ in combination with `/etc/fstab` to mount the datasets at the correct time. Based on the description from the [ZoL-Guide](https://github.com/zfsonlinux/zfs/wiki/Ubuntu-18.04-Root-on-ZFS):

- Create `zfs-import-bpool.service` for importing `bpool`
- Create a shell script with the following content:
```
# Note: I had to add `zedenv list -a` which displays only the active boot environment.
BE=`zedenv list -H -a | cut -f1`
/bin/mount -t zfs "bpool/boot/env/zedenv-$BE" /boot
```
- Create `zfs-import-zedenv-boot-env.service` which calls the custom shell script from the previous step.
- Define some datasets as legacy and add them in `/etc/fstab`.
- For `bpool/boot/grub`, use `x-systemd.requires=zfs-import-zedenv-boot-env.service` to make sure `/boot` is mounted before `/boot/grub`.

Best regards
Markus

**Comment by johnramsden** [comment]
Sounds good, looking forward to taking a look at the PR.
