### ISSUE TITLE
Bootloader entries should be created on `create`, not `activate`

### ISSUE THREAD

**Issue by zhimsel** [johnramsden/zedenv#23]
I'm talking about the `systemd-boot` plugin specifically, but this can/should be treated globally.

It feels more intuitive that when a boot env is created, it should be available in the bootloader as an entry. However, the bootloader entry/kernel directory/etc aren't created until `activate` is run.

I'm looking through the code, and this certainly seems possible. I'm very tempted to write up a PR to make this change, but before I do, I wanted to discuss the feasibility and impact of making such a change.

The "edit BE `/fstab` and create booloader entries" step seems pretty tied to the `mid-activate` step. It can easily be moved to `post-create`, but a LOT of other references will need to be updated and some of the CLI code possibly refactored.

I'm curious as to why the decision was made to modify the BE and create bootloader entries during activation instead of creation?

Thoughts?

**Comment by zhimsel** [comment]
An example scenario of where the current behavior can be annoying:

I want to update my kernel, but before I do, I want to create a backup BE. So I run `zedenv create new-env`. In order to boot to this, I need to run `zedenv activate new-env` first.

However, I only want to boot to it if the kernel upgrade (in the current BE) fails. Meaning I either need to `zedenv activate original-env`, or manually select the original BE in the bootloader.

Once the kernel upgrade runs successfully, I can then destroy `new-env`.

By making the proposed change above, the only step needed here is `zedenv create`, and if the upgrade fails, I just reboot and _then_ manually select the backup env.

**Comment by tlaguz** [comment]
I just ran into this while trying out zedenv. I also expected it to work this way.

**Comment by zhimsel** [comment]
Just a note for anyone who is experiencing this as well. This issue has been fixed in a soon-to-be-released rewrite of zedenv called zectl.

**Comment by johnramsden** [comment]
For anyone referring to this issue. New development has moved to [zectl](https://github.com/johnramsden/zectl), where this issue has been fixed. I agree the behaviour is unexpected and was a bad design decision initially. In the new version of the software configuration files are created on `create`.
