### ISSUE TITLE
get --defaults fails

### ISSUE THREAD

**Issue by danboid** [johnramsden/zedenv#7]
I have installed zedenv-git and the grub-generators branch of zedenv-grub as per these instructions on an ALEZ 0.4 VM:

```
Building zedenv packages from git under Arch

mkdir ~/src && cd ~/src

# Build pyzfscmds arch package
git clone https://github.com/johnramsden/pyzfscmds.git
cd pyzfscmds/packaging/arch/
makepkg -s -p PKGBUILD-git
# Install pyzfscmds package
sudo pacman -U python-pyzfscmds-git-r38.8423bca-1-any.pkg.tar.xz

# Build zedenv Arch package
cd ~/src
git clone https://github.com/johnramsden/zedenv.git
cd zedenv/packaging/arch/
makepkg -s -p PKGBUILD-git
# Install zedenv package
sudo pacman -U zedenv-git-r142.8af5752-1-any.pkg.tar.xz

# Build grub-generators branch of zedenv-grub
cd ~/src
git clone https://github.com/johnramsden/zedenv-grub.git
cd zedenv-grub/
git checkout grub-generators
cd packaging/arch/
makepkg -s -p PKGBUILD-git
sudo pacman -U zedenv-grub-git-r124.7011da2-1-any.pkg.tar.xz
```

According to your instructions at https://github.com/johnramsden/zedenv-grub/blob/docs/README.rst I really need to configure the grub plugin before I use zedenv but I have just tried running `zedenv get --defaults` as both root and a normal user and I get this error:

```
[root@archlinux zedenv-grub]# zedenv get --defaults
Traceback (most recent call last):
  File "/usr/bin/zedenv", line 11, in <module>
    load_entry_point('zedenv==0.3.1', 'console_scripts', 'zedenv')()
  File "/usr/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/zedenv/cli/get.py", line 172, in cli
    zedenv.lib.be.root())
  File "/usr/lib/python3.7/site-packages/zedenv/cli/get.py", line 115, in zedenv_get
    for bl in zedenv.lib.configure.get_bootloader_properties():
  File "/usr/lib/python3.7/site-packages/zedenv/lib/configure.py", line 28, in get_bootloader_properties
    "properties": plugins[p].allowed_properties
AttributeError: type object 'GRUB' has no attribute 'allowed_properties'
```

**Comment by johnramsden** [comment]
Do the non-git versions of `zedenv` and `pyzfscmds` work?

**Comment by danboid** [comment]
[dan@archlinux arch]$ pwd
/home/dan/src/pyzfscmds/packaging/arch
[dan@archlinux arch]$ makepkg -s
==> Making package: python-pyzfscmds 0.1.3-1 (Sun Oct 14 02:24:53 2018)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading python-pyzfscmds-0.1.3.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   134    0   134    0     0    236      0 --:--:-- --:--:-- --:--:--   235
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
==> ERROR: Failure while downloading https://github.com/johnramsden/pyzfscmds/archive/v0.1.3-beta.tar.gz
    Aborting...

**Comment by johnramsden** [comment]
The package builds in the `pyzfscmds` in master aren't really working, maybe use the one from the AUR.

**Comment by johnramsden** [comment]
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-pyzfscmds

**Comment by danboid** [comment]
I'm starting to get a bit lost amongst the varying versions, branches and PKGBUILDs required to test this now.

So, if I understand you so far, I should:

* Install the default pyzfscmds from AUR
* Install Master / 'non-git' zedenv from git (or AUR?)
* Install grub-generators, edited PKGBUILD-git version of the grub plugin

I tend not use use AUR helpers to build smaller packages like these so I'd like to see the PKGBUILDs on github for all three projects be updated so as to work. AUR helpers seem to come and go quite quickly, unlike makepkg.

**Comment by johnramsden** [comment]
@danboid Yes that's correct. I'll fix up the `PKGBUILDS` so they match the AUR, sorry for the confusion.

**Comment by danboid** [comment]
Thanks John!

**Comment by danboid** [comment]
I'd prefer to test zedenv by using the PKGBUILDS included with the source with no requirement to use the AUR . That seems like 'the right way' to me.

**Comment by johnramsden** [comment]
Hopefully that sorts out the issue with the `PKGBUILDS`, let me know if you have any other trouble.
