### ISSUE TITLE
Fails to find `default` entry in `loader.conf` with preceding whitespaces (systemd-boot)

### ISSUE THREAD

**Issue by TPKato** [johnramsden/zedenv#9]
`zedenv` fails to find the `default` entry in the `loader.conf` file during activating a BE if the line has preceding white spaces.
See l.226 of `plugins/systemdboot.py`.

        line_num = next((l for l, val in enumerate(conf_list)
	        if val.split(' ', 1)[0] == "default"), None)

`val.split()` returns `''` (empty string) if the line contains preceding white spaces.
Note that `ALEZ` makes a `/mnt/efi/loader/loader.conf` with preceding white spaces.

I think the preceding white spaces should be omitted before `split()`.

----

FYI: The manpage of `loader.conf`(5) says only

> Each configuration file must consist of an option name, followed by whitespace, and the option value.

It seems that `systemd` removes the leading (and trailing) white spaces while reading `loader.conf` in 
[`boot/efi/boot.c`](https://github.com/systemd/systemd/blob/master/src/boot/efi/boot.c).

**Comment by johnramsden** [comment]
Fixed in de6d8b7

Thanks for reporting the bugs.
